/**
 * Widget catalog — every widget type the dashboard can render.
 * Add new widgets here and wire them in `widget-renderer.tsx`.
 */

import type { WidgetDefinition } from "./types";

export const WIDGET_CATALOG: WidgetDefinition[] = [
  // ─── Metrics ──────────────────────────────────────────────
  {
    type: "metric-net-balance",
    category: "Metrics",
    title: "Net Balance",
    description: "Total across all asset accounts",
    icon: "Wallet",
    defaultSize: { w: 3, h: 1 },
    minSize: { w: 2, h: 1 },
    maxSize: { w: 6, h: 2 },
    previewAccent: "from-emerald-400 to-teal-500",
  },
  {
    type: "metric-monthly-spending",
    category: "Metrics",
    title: "Monthly Spending",
    description: "Expenses this month",
    icon: "ArrowDownRight",
    defaultSize: { w: 3, h: 1 },
    minSize: { w: 2, h: 1 },
    maxSize: { w: 6, h: 2 },
    previewAccent: "from-rose-400 to-red-500",
  },
  {
    type: "metric-monthly-income",
    category: "Metrics",
    title: "Monthly Income",
    description: "Income this month",
    icon: "ArrowUpRight",
    defaultSize: { w: 3, h: 1 },
    minSize: { w: 2, h: 1 },
    maxSize: { w: 6, h: 2 },
    previewAccent: "from-sky-400 to-blue-500",
  },
  {
    type: "metric-net-lending",
    category: "Metrics",
    title: "Net Lending",
    description: "What you're owed minus what you owe",
    icon: "HandCoins",
    defaultSize: { w: 3, h: 1 },
    minSize: { w: 2, h: 1 },
    maxSize: { w: 6, h: 2 },
    previewAccent: "from-amber-400 to-orange-500",
  },
  {
    type: "metric-liabilities",
    category: "Metrics",
    title: "Total Liabilities",
    description: "Credit cards, loans, other debts",
    icon: "CreditCard",
    defaultSize: { w: 3, h: 1 },
    minSize: { w: 2, h: 1 },
    maxSize: { w: 6, h: 2 },
    previewAccent: "from-fuchsia-400 to-purple-500",
  },
  {
    type: "metric-savings-rate",
    category: "Metrics",
    title: "Savings Rate",
    description: "Percent of income saved this month",
    icon: "PiggyBank",
    defaultSize: { w: 3, h: 1 },
    minSize: { w: 2, h: 1 },
    maxSize: { w: 6, h: 2 },
    previewAccent: "from-lime-400 to-green-500",
  },

  // ─── Charts ───────────────────────────────────────────────
  {
    type: "chart-net-worth",
    category: "Charts",
    title: "Net worth over time",
    description: "Track how your wealth evolves",
    icon: "TrendingUp",
    defaultSize: { w: 6, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 12, h: 5 },
    supportsChartTypes: ["line", "area", "bar"],
    previewAccent: "from-blue-400 to-indigo-500",
  },
  {
    type: "chart-cash-flow",
    category: "Charts",
    title: "Cash flow",
    description: "Income vs expenses, monthly",
    icon: "BarChart3",
    defaultSize: { w: 6, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 12, h: 5 },
    supportsChartTypes: ["bar", "line", "area"],
    previewAccent: "from-teal-400 to-cyan-500",
  },
  {
    type: "chart-spending-by-category",
    category: "Charts",
    title: "Spending by category",
    description: "Where your money went",
    icon: "PieChart",
    defaultSize: { w: 6, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 12, h: 5 },
    supportsChartTypes: ["pie", "bar"],
    previewAccent: "from-pink-400 to-rose-500",
  },
  {
    type: "chart-income-vs-expenses",
    category: "Charts",
    title: "Income vs expenses",
    description: "Side-by-side monthly comparison",
    icon: "Scale",
    defaultSize: { w: 6, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 12, h: 5 },
    supportsChartTypes: ["bar", "area"],
    previewAccent: "from-violet-400 to-purple-500",
  },

  // ─── Lists ────────────────────────────────────────────────
  {
    type: "list-accounts",
    category: "Lists",
    title: "Accounts",
    description: "Quick view of all your accounts",
    icon: "Wallet",
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 12, h: 6 },
    previewAccent: "from-slate-400 to-slate-500",
  },
  {
    type: "list-upcoming-bills",
    category: "Lists",
    title: "Upcoming bills",
    description: "Due in the next 14 days",
    icon: "CalendarClock",
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 8, h: 5 },
    previewAccent: "from-yellow-400 to-amber-500",
  },
  {
    type: "list-recent-transactions",
    category: "Lists",
    title: "Recent transactions",
    description: "Latest activity across accounts",
    icon: "Receipt",
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 2 },
    maxSize: { w: 12, h: 6 },
    previewAccent: "from-emerald-400 to-green-500",
  },
  {
    type: "list-top-categories",
    category: "Lists",
    title: "Top categories",
    description: "Biggest spending categories",
    icon: "ListOrdered",
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 8, h: 5 },
    previewAccent: "from-orange-400 to-red-500",
  },

  // ─── Activity ─────────────────────────────────────────────
  {
    type: "inbox-alerts",
    category: "Activity",
    title: "Alerts",
    description: "Things that need your attention",
    icon: "Bell",
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 8, h: 5 },
    previewAccent: "from-red-400 to-pink-500",
  },
  {
    type: "inbox-needs-context",
    category: "Activity",
    title: "Needs context",
    description: "SMS transactions awaiting enrichment",
    icon: "Inbox",
    defaultSize: { w: 6, h: 2 },
    minSize: { w: 3, h: 1 },
    maxSize: { w: 12, h: 4 },
    previewAccent: "from-cyan-400 to-blue-500",
  },
  {
    type: "stat-accounts-count",
    category: "Activity",
    title: "Accounts count",
    description: "How many accounts you track",
    icon: "Hash",
    defaultSize: { w: 2, h: 1 },
    minSize: { w: 2, h: 1 },
    maxSize: { w: 4, h: 2 },
    previewAccent: "from-gray-400 to-gray-500",
  },
  {
    type: "stat-transactions-this-month",
    category: "Activity",
    title: "Transactions this month",
    description: "Total count",
    icon: "Activity",
    defaultSize: { w: 2, h: 1 },
    minSize: { w: 2, h: 1 },
    maxSize: { w: 4, h: 2 },
    previewAccent: "from-indigo-400 to-blue-500",
  },

  // ─── Custom ───────────────────────────────────────────────
  {
    type: "note-heading",
    category: "Custom",
    title: "Section heading",
    description: "A text heading to group widgets",
    icon: "Heading",
    defaultSize: { w: 12, h: 1 },
    minSize: { w: 4, h: 1 },
    maxSize: { w: 12, h: 2 },
    previewAccent: "from-neutral-300 to-neutral-400",
  },
];

export const CATEGORY_ORDER = [
  "Metrics",
  "Charts",
  "Lists",
  "Activity",
  "Custom",
] as const;

export function getWidgetDefinition(type: string): WidgetDefinition | undefined {
  return WIDGET_CATALOG.find((w) => w.type === type);
}
